# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import faiss_service_pb2 as faiss__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in faiss_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaissServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendShard = channel.stream_unary(
                '/faiss_dist.FaissService/SendShard',
                request_serializer=faiss__service__pb2.ShardRequest.SerializeToString,
                response_deserializer=faiss__service__pb2.ShardResponse.FromString,
                _registered_method=True)
        self.TrainIndex = channel.unary_unary(
                '/faiss_dist.FaissService/TrainIndex',
                request_serializer=faiss__service__pb2.TrainRequest.SerializeToString,
                response_deserializer=faiss__service__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.SearchBatch = channel.unary_unary(
                '/faiss_dist.FaissService/SearchBatch',
                request_serializer=faiss__service__pb2.SearchBatchRequest.SerializeToString,
                response_deserializer=faiss__service__pb2.SearchBatchResponse.FromString,
                _registered_method=True)


class FaissServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendShard(self, request_iterator, context):
        """stream a shard of vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainIndex(self, request, context):
        """train an IVF on that shard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBatch(self, request, context):
        """batch k‑NN search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaissServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendShard': grpc.stream_unary_rpc_method_handler(
                    servicer.SendShard,
                    request_deserializer=faiss__service__pb2.ShardRequest.FromString,
                    response_serializer=faiss__service__pb2.ShardResponse.SerializeToString,
            ),
            'TrainIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainIndex,
                    request_deserializer=faiss__service__pb2.TrainRequest.FromString,
                    response_serializer=faiss__service__pb2.TrainResponse.SerializeToString,
            ),
            'SearchBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBatch,
                    request_deserializer=faiss__service__pb2.SearchBatchRequest.FromString,
                    response_serializer=faiss__service__pb2.SearchBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faiss_dist.FaissService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('faiss_dist.FaissService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaissService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendShard(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/faiss_dist.FaissService/SendShard',
            faiss__service__pb2.ShardRequest.SerializeToString,
            faiss__service__pb2.ShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faiss_dist.FaissService/TrainIndex',
            faiss__service__pb2.TrainRequest.SerializeToString,
            faiss__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faiss_dist.FaissService/SearchBatch',
            faiss__service__pb2.SearchBatchRequest.SerializeToString,
            faiss__service__pb2.SearchBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
