# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: faiss_service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'faiss_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x61iss_service.proto\x12\nfaiss_dist\"=\n\x0cShardRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12\x12\n\ncluster_id\x18\x03 \x01(\x05\"\x1b\n\rShardResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"1\n\x0cTrainRequest\x12\r\n\x05nlist\x18\x01 \x01(\x05\x12\x12\n\ncluster_id\x18\x02 \x01(\x05\"*\n\rTrainResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"T\n\rSearchRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\x12\x14\n\x0cquery_vector\x18\x02 \x03(\x02\x12\t\n\x01k\x18\x03 \x01(\x05\x12\x0e\n\x06nprobe\x18\x04 \x01(\x05\"A\n\x12SearchBatchRequest\x12+\n\x08requests\x18\x01 \x03(\x0b\x32\x19.faiss_dist.SearchRequest\"K\n\x0eSearchResponse\x12\x11\n\tdistances\x18\x01 \x03(\x02\x12\x0f\n\x07indices\x18\x02 \x03(\x03\x12\x15\n\rerror_message\x18\x03 \x01(\t\"D\n\x13SearchBatchResponse\x12-\n\tresponses\x18\x01 \x03(\x0b\x32\x1a.faiss_dist.SearchResponse2\xe5\x01\n\x0c\x46\x61issService\x12\x42\n\tSendShard\x12\x18.faiss_dist.ShardRequest\x1a\x19.faiss_dist.ShardResponse(\x01\x12\x41\n\nTrainIndex\x12\x18.faiss_dist.TrainRequest\x1a\x19.faiss_dist.TrainResponse\x12N\n\x0bSearchBatch\x12\x1e.faiss_dist.SearchBatchRequest\x1a\x1f.faiss_dist.SearchBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faiss_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHARDREQUEST']._serialized_start=35
  _globals['_SHARDREQUEST']._serialized_end=96
  _globals['_SHARDRESPONSE']._serialized_start=98
  _globals['_SHARDRESPONSE']._serialized_end=125
  _globals['_TRAINREQUEST']._serialized_start=127
  _globals['_TRAINREQUEST']._serialized_end=176
  _globals['_TRAINRESPONSE']._serialized_start=178
  _globals['_TRAINRESPONSE']._serialized_end=220
  _globals['_SEARCHREQUEST']._serialized_start=222
  _globals['_SEARCHREQUEST']._serialized_end=306
  _globals['_SEARCHBATCHREQUEST']._serialized_start=308
  _globals['_SEARCHBATCHREQUEST']._serialized_end=373
  _globals['_SEARCHRESPONSE']._serialized_start=375
  _globals['_SEARCHRESPONSE']._serialized_end=450
  _globals['_SEARCHBATCHRESPONSE']._serialized_start=452
  _globals['_SEARCHBATCHRESPONSE']._serialized_end=520
  _globals['_FAISSSERVICE']._serialized_start=523
  _globals['_FAISSSERVICE']._serialized_end=752
# @@protoc_insertion_point(module_scope)
